### ISSUE TITLE
Missing STL for rod housings

### ISSUE THREAD

**Issue by roboboogie** [OccasionalThingMaker/rudder-pedals#10]
Appolgies if I'm wrong but we're possibly missing the socket for the ends of the metal rods as pictured?

**Comment by OccasionalThingMaker** [comment]
You're right. Uploaded it now as "rod-bracket v2.stl"
I would advice to test print parts of the pieces and check how they fit, as the tolerances were made for my printer. You can adjust them as needed with "XY Size Compensation" (name in prusaslicer, could be different in other slicers) as needed.

**Comment by roboboogie** [comment]
Thank you! Really appreciate you sharing tall of this.
